version: "3"

services:
 
  api1:
    image: prac5d_737 
    container_name: docker-node-5d
    ports:
      - "3000:3000"
    networks:
      - my-network

  ui:
    image: prac5dui_737 
    container_name: docker-node-5dui
    ports:
      - "4200:80"
    environment:
      - SERVER_NAME=api1
    networks:
      - my-network


networks:
  my-network:
    driver: bridge
